name: trade_producer
language: python
variables:
  - name: KAFKA_TOPIC
    inputType: OutputTopic
    description: The kafka topic where the trade data is saved
    defaultValue: trade
    required: true
  - name: PRODUCT_IDS
    inputType: FreeText
    description: List of product ids to fetch from Kraken API
    defaultValue: "'[\"BTC/USD\", \"ETH/EUR\", \"ETH/USD\"]'"
    required: true
  - name: LIVE_OR_HISTORICAL
    inputType: FreeText
    description: Where to connect to Kraken Websocket for live data or REST API for historical data
    defaultValue: live
    required: true
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
