name: price_predictor
language: python
variables:
  - name: HOPSWORKS_API_KEY
    inputType: Secret
    description: The feature store API key
    defaultValue: HOPSWORKS_API_KEY
    required: true
  - name: HOPSWORKS_PROJECT_NAME
    inputType: Secret
    description: The feature store project name
    defaultValue: HOPSWORKS_PROJECT_NAME
    required: true
  - name: COMET_ML_API_KEY
    inputType: Secret
    description: The model registry and experiment tracker API key
    defaultValue: COMET_ML_API_KEY
    required: true
  - name: COMET_ML_PROJECT_NAME
    inputType: Secret
    description: The experiment tracker and model registry project name
    defaultValue: COMET_ML_PROJECT_NAME
    required: true
  - name: COMET_ML_WORKSPACE
    inputType: Secret
    description: The experiment tracker and model registry workspace name
    defaultValue: COMET_ML_WORKSPACE
    required: true
dockerfile: Dockerfile
runEntryPoint: src/api.py
defaultFile: src/api.py
