# Docker compose with 3 services: trade_producer, trade_to_ohlc, kafka_to_feature_store
version: "3.7"
name: feature_pipeline
networks:
  redpanda_network:
    name: redpanda_network
    driver: bridge
    
services:
  trade_producer:
    #container_name: trade_producer
    build:
      context: ../services/trade_producer
    networks:
      - redpanda_network
    environment:
      KAFKA_BROKER_ADDRESS: redpanda-0:9092
    env_file:
      - ../services/trade_producer/setup_live_config.sh
    restart: always
  
  trade_to_ohlc:
    #container_name: trade_to_ohlc
    build:
      context: ../services/trade_to_ohlc
    networks:
      - redpanda_network
    environment:
      KAFKA_BROKER_ADDRESS: redpanda-0:9092
    env_file:
      - ../services/trade_to_ohlc/setup_live_config.sh
    restart: always

  kafka_to_feature_store:
    #container_name: kafka_to_feature_store
    build:
      context: ../services/kafka_to_feature_store
    networks:
      - redpanda_network
    environment:
      KAFKA_BROKER_ADDRESS: redpanda-0:9092
    env_file:
      - ../services/kafka_to_feature_store/setup_live_config.sh
      - ../services/kafka_to_feature_store/setup_credentials.sh
    restart: always