start-redpanda:
	docker compose -f redpanda.yml up -d 

stop-redpanda:
	docker compose -f redpanda.yml down

run-feature-pipeline:
	docker compose -f feature-pipeline.yml up -d

stop-feature-pipeline:
	docker compose -f feature-pipeline.yml down