name: kafka_to_feature_store
language: python
variables:
  - name: KAFKA_TOPIC
    inputType: InputTopic
    description: The Kafka topic to ingest OHLC data from
    defaultValue: ohlc
    required: true
  - name: KAFKA_CONSUMER_GROUP
    inputType: FreeText
    description: ' Creating data from the ohlc topic'
    defaultValue: ohlc_consumer_group_99
    required: true
dockerfile: Dockerfile
runEntryPoint: sc/main.py
defaultFile: src/main.py
