name: kafka_to_feature_store
language: python
variables:
  - name: KAFKA_TOPIC
    inputType: InputTopic
    description: The Kafka topic to ingest OHLC data from
    defaultValue: ohlc
    required: true
  - name: KAFKA_CONSUMER_GROUP
    inputType: FreeText
    description: ' Creating data from the ohlc topic'
    defaultValue: ohlc_consumer_group_99
    required: true
  - name: FEATURE_GROUP_NAME
    inputType: FreeText
    description: The feature store feature group name
    defaultValue: ohlc_feature_group
    required: true
  - name: FEATURE_GROUP_VERSION
    inputType: FreeText
    description: The feature group version
    defaultValue: 1
    required: true
  - name: BUFFER_SIZE
    inputType: FreeText
    description: Number of messages to push at once
    defaultValue: 1
    required: true
  - name: LIVE_OR_HISTORICAL
    inputType: FreeText
    description: ''
    defaultValue: live
    required: true
  - name: HOPSWORKS_PROJECT_NAME
    inputType: Secret
    description: The feature store project name
    defaultValue: HOPSWORKS_PROJECT_NAME
    required: true
dockerfile: Dockerfile
runEntryPoint: sc/main.py
defaultFile: src/main.py
